common/utils.py
iap/api/purchase.py
iap/iap_cdk_stack.py
iap/settings/__init__.py
poetry.lock
pyproject.toml
worker/worker/handler.py
worker/worker/tracker.py
worker/worker_cdk_stack.py

IAP purchase is not automatically consumed when it's purchased and can be easily cancelled by buyer.
To prevent this, purchase validation function executes consume function.

Consume purchase immediately

---

iap/api/purchase.py

GET method should retrieve data from query parameter, not JSON requset body.

`/purchase/states` gets UUIDs from query parameter

---

app.py
common/_crypto.py
common/_graphql.py
common/consts.py
iap/api/purchase.py
iap/iap_cdk_stack.py
iap/settings/__init__.py
iap/validator/common.py
worker/template.yml.example
worker/worker/handler.py
worker/worker_cdk_stack.py

- Unify confusing env. variable names.
- Add AWS permissions to send SQS message, Sign Tx.
- Fix getting wrong product to give.

Fix bugs in Tx. creating and requesting logic

---

.github/workflows/deploy.yml
common/__init__.py
common/_graphql.py
common/utils.py
iap/iap_cdk_stack.py
iap/main.py
iap/settings/__init__.py
worker/worker/updater.py
worker/worker_cdk_stack.py

- Add `GOOGLE_PACKAGE_NAME`
- Get `GOOGLE_CREDENTIAL` from parameter store
- Exclude `.github` from CDK stack
- Change all `ENV` to `STAGE`

Update google related settings

---

iap/iap_cdk_stack.py
iap/settings/__init__.py

Create config from os.environ

---

.github/workflows/deploy.yml

Add missing env. variables in deploy step

---

iap/api/purchase.py

Exclude current receipt when counting purchase count to check purchase limit

Don't count current receipt

---

iap/api/purchase.py

Missing code: Update status for weekly limit

---

common/enums.py
iap/frontend/src/const.js

Add missing `PURCHASE_LIMIT_EXCEED` status into `const.js`

Add missing receipt status

---

iap/schemas/product.py

Add deleted field while resolving conflict

---

.github/workflows/deploy.yml

Send slack message after CDK deployment

---

iap/api/product.py
iap/utils.py

Get IAP balance from headless GQL and check buyability

---

iap/iap_cdk_stack.py

API needs GetPublicKey permission to get IAP address

---

.github/workflows/build_frontend.yml
.github/workflows/build_layer.yml
.github/workflows/deploy.yml
.github/workflows/main.yml
.github/workflows/slack_message.yml
.github/workflows/test.yml

Update github actions

---

.github/workflows/build_frontend.yml
.github/workflows/build_layer.yml
.github/workflows/deploy.yml
.github/workflows/main.yml
.github/workflows/slack_message.yml
.github/workflows/test.yml
iap/iap_cdk_stack.py

[Backmerge] Release/0.1.1 to development

---

common/utils.py
iap/api/product.py
iap/utils.py
worker/worker/garage_noti.py
worker/worker_cdk_stack.py

IAP Garage notification everyday

---

common/_crypto.py
common/utils.py

- To avoid circular import
- `_crypto` is the only usage

Move "derive_address" function to _crypto module

---

common/shared_stack.py

Add missing movement

---

iap/main.py
worker/worker_cdk_stack.py

- Log all incoming API request URLs
- Run price updater / garage reporter only when stage not in `internal`

Enhanced logging

---

worker/worker/golden_dust_by_ncg.py
worker/worker_cdk_stack.py

- Save IAP nonce and plain values for future
- Set detailed invalid status: can/cannot refund

Improve golden dust worker

---

app.py

Add tgas to AWS resources

---

common/shared_stack.py

Change to resolve mainnet deployment error

Extend SQS message visibility to lambda execution limit

---

iap/utils.py

Function does not accept filter_by. Use filter

---

iap/api/product.py
iap/api/purchase.py

Set all addresses to lower case

---

worker/worker/handler.py

Remove non-existing function

---

iap/iap_cdk_stack.py

This could be wrong. Test and verify needed.

Add custom domain: api.9c.gg

---

.github/workflows/deploy.yml
.github/workflows/synth.yml
common/__init__.py
common/_crypto.py
iap/api/purchase.py
iap/iap_cdk_stack.py
iap/schemas/receipt.py
worker/worker/handler.py
worker/worker_cdk_stack.py

- Use `PLANET_URL` to get bridge addresses
- Set default planet by network

Update multiplanetary appicances

---

iap/api/product.py
iap/utils.py

Consider planet_id when checking purchase_limit

---

worker/worker/handler.py

Send product SKU into memo

---

iap/api/product.py

Fix wrong import

---

common/_graphql.py
iap/api/product.py
iap/api/purchase.py
iap/utils.py
worker/worker/manual.py
worker/worker/tracker.py

- Track tx by planet
- Check purchase limit by planet
- Use custom logger
- Save error messages
- Track `INVALID` Tx.s too

Apply multiplanetary

---

worker/worker/manual.py

Add root package name

---

worker/worker/handler.py

SSIA
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205954855116567

Memo in bridge must include recipient address

---

iap/api/purchase.py

- Fix wrong names from IAP to seasonpass

Fix wrong names

---

worker/worker/tracker.py

Fix wrong statement

---

iap/api/product.py
iap/api/purchase.py
iap/utils.py

- Daily limit: in today
- Weekly limit: in this week (Sun~Sat)
- All limits will be reset at 00:00 UTC

Fix purchase limit calculating logic

---

worker/worker/handler.py

✨  introduce: structured logging for worker

---

worker/worker/handler.py

fix: reference first

---

common/models/receipt.py

🔧  impl: receipt.__dict__

---

common/models/receipt.py
worker/worker/handler.py

fix: wrong serialize

---

worker/worker/handler.py

fix: worker result field

---

worker/worker/handler.py

fix: do not multiple line

---

iap/api/purchase.py

Fix import path

---

worker/worker/handler.py

- use context manager instead of try-catch.
- raise the exception, do not ignore.

fix: use context manager instead of try-catch

---

worker/worker/golden_dust_by_ncg.py
worker/worker/handler.py

Select internal planet if not in mainnet

---

worker/worker/handler.py

fix: do not ignore exception

---

common/lib9c/currency.py

Fix wrong decimal places string

---

worker/worker/handler.py

Add internal headless addresses

---

common/lib9c/fungible_asset.py
common/models/product.py
common/utils/actions.py
tests/lib9c/test_fungible_asset.py
tests/utils/test_actions.py

Apply decimalPlacecs when creating Tx

---

common/shared_stack.py

This is lambda-SQS restriction.

Set visibility timeout >= function timeout

---

worker/worker/voucher.py

Not begin transaction to use session as a session

---

.github/workflows/test.yml
iap/schemas/product.py
tests/common/schemas/test_product_schema.py
tests/lib9c/test_currency.py
tests/lib9c/test_fungible_asset.py
tests/test_image_link.py

Same as #178 but goes to 0.8.0

Split FAV ticker by dunder to get real ticker

---

.github/workflows/deploy.yml
.github/workflows/main.yml
.github/workflows/synth.yml
worker/worker/google_refund_tracker.py
worker/worker_cdk_stack.py

Get voided purchases (refund) from google API and store it to google sheet everyday.

Store google refund to sheet

---

iap/api/purchase.py

Send voucher request after validation

---

worker/worker/status_monitor.py

Not begin transaction before create and run query

---

iap/api/product.py

This can cause bad user experience: block buying product without explanation.
Don't block buyability from garage status
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206136783593016

Do not check buyable by DB saved garage status

---

common/models/product.py

Load product list with ordering

---

iap/api/purchase.py
worker/worker/voucher.py

- Fix message format: use `receipt_id`
- Log all exceptions as-is

Fix handling exception

---

common/consts.py

Add soulstones to avatar bound ticker

---

.github/workflows/test.yml

Use test validation url for test

---

iap/api/purchase.py

product_id is not in data for free product

---

.github/workflows/deploy.yml
.github/workflows/synth.yml
common/__init__.py
iap/api/purchase.py
iap/iap_cdk_stack.py

Add GQL for each planet and find avatar data from right planet

Find avatar in right planet

---

worker/worker/status_monitor.py

- Add stage into title to check network
- Sort garage data in certain order

Update garage slack message

---

common/lib9c/models/fungible_asset_value.py
worker/worker/status_monitor.py

Backmerge 0.10.0 to development

---

iap/api/purchase.py

- Create validation functions
- purchase limit
- required level
- Check required level for IAP product, not only free product.

Check required level for IAP products

---

worker/worker/status_monitor.py

Ruby dust is added into product.
Monitor this asset and report daily.

Add ruby dust into statut monitor

---

iap/api/purchase.py
iap/iap_cdk_stack.py

- Add ruby dust
- Add level requirement to IAP products

Backmerge 0.11.0 to development

---

iap/api/purchase.py
iap/validator/google.py

Ack valid purchase

---

iap/api/purchase.py
iap/schemas/receipt.py

- Get package_name from request header and validate receipt based on it.
- Save package_name into DB (Receipt Table)

Features for 9c K

---

iap/api/purchase.py
iap/validator/apple.py
tests/iap/api/test_purchase.py

Use package name from DB, not from default setting

Use proper package name for apple validation

---

iap/api/l10n.py
iap/api/product.py
iap/api/purchase.py
iap/validator/apple.py
tests/iap/api/test_purchase.py

Backmerge 1.0.0 release to development

Backmerge 1.0.0

---

iap/api/purchase.py

Package name is also required to create receipt

Set default header and save to receipt for free packages

---

iap/api/purchase.py

- Add apple_k SKU when finding product
- Update error message for free purchase

Check sku for K

---

iap/api/purchase.py
iap/schemas/product.py
worker/worker/handler.py

To make client to find all product regardless application/platform, Add `apple_sku_k` field into Product schema

Add apple_sku_k into product schema

---

iap/api/purchase.py
worker/worker_cdk_stack.py

`package_name` is need to distinguish and put right L10N product name within client.

Add package_name into SQS message

---

common/lib9c/actions/issue_tokens_from_garage.py

Need common path to load common library

---

common/lib9c/actions/transfer_assets.py
tests/lib9c/actions/test_transfer_assets.py
worker/worker/manual/transfer_assets.py
worker/worker_cdk_stack.py

- Port TransferAssets action from lib9c
- Add manual lambda function

Introduce TransferAssets action

---

worker/worker/status_monitor.py
worker/worker/tracker.py
worker/worker_cdk_stack.py

From 2.0.0, IAP gives item using ClaimItems from IAP account in each planet.
To track this, update tx. tracker function to track tx. with proper planet GQL URL.

Track Tx by planet

---

iap/api/purchase.py

Fix request season setting logic: use all numeric

---

iap/api/purchase.py
worker/worker/handler.py

Sometimes when lots of requests comes in at once, heimdall nonce is confused with odin's.
To resolve this, make nonce_dict and get nonce by planet.

Use nonce_dict by planet

---

common/utils/address.py
iap/api/mileage.py
iap/api/product.py
iap/main.py
iap/schemas/receipt.py
iap/utils.py
tests/utils/address_test.py

- Use formatted address to make new mileage
- Commit new mileage when created

Fix things

---

.github/workflows/main.yml

Internal branch need to be deployed to internal IAP service

Test and deploy for internal branch

---

iap/api/purchase.py

All the JWT node request needs JWT header

Use JWT header to get avatar addr

---

worker/worker/status_monitor.py

Add thor rune and golden meat to monitor

---

iap/api/mileage.py
iap/schemas/mileage.py
iap/utils.py
worker/worker/handler.py
worker/worker/tracker.py

Backmerge 2.2.1 to development

Backmerge 2.2.1

---

common/lib9c/actions/burn_asset.py
common/lib9c/actions/issue_token.py
worker/worker/manual/burn_asset.py
worker/worker/manual/issue_token.py

Fix import to make function works.

Fix wrong import: import from root

---

iap/api/__init__.py
worker/worker/status_monitor.py

Add balance check API for assertible and manual check

Add balance monitor API including soulstones

---

iap/api/purchase.py

- Remove planet
- Add product_id to check certain product
- [TBD] Join price

Update purchase history API

---

backoffice/templates/products.html

- 정렬 기능 추가
- 테이블 영역이 벗어나서 스타일 깨지는 문제 해결
---
AS-IS
TO-BE

상품목록 페이지 개선

---

worker/worker/handler.py

Update purchase history API for PetPoP quest

---

backoffice/main.py
backoffice/templates/base.html
backoffice/templates/receipts.html

- resolve #383 
- Added a new endpoint to list receipts with specific filters.
- Created a new template for displaying the receipts.
- Updated the navigation to include a link to the receipts page.
- Enhanced database queries to fetch valid receipts while excluding certain products.

Implement receipt listing feature

---

iap/api/admin.py

This API gets price info from play store and put into DB.

Remove update-price admin API

---

iap/api/admin.py
worker/worker/status_monitor.py

This goes to main and deploy to production.

Remove update-product admin API
